name: Test notebooks

on:
    push:
        branches:
            - main
            # - master

    pull_request:
        branches:
            - main
            # - master

    workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: ['1.9']
        julia-arch: [x64]
        os: [ubuntu-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
          arch: ${{ matrix.julia-arch }}
      - name: Cache something
        uses: julia-actions/cache@v1
      # Commented out since lab notebooks aren't packages to be built
      - name: Build Package
        uses: julia-actions/julia-buildpkg@v1
      - name: Instal test/notebook dependencies
        run: julia test/instantiate.jl
      - name: Run Tests
        uses: julia-actions/julia-runtest@v1
